import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ThemeToggle } from "./components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="relative min-h-screen flex flex-col bg-[#98A869] dark:bg-zinc-900">

  {/* animated light layer */}
  <div
    className="
      fixed inset-0 -z-10
      transition-opacity duration-700 ease-in-out
      bg-[#98A869]
      dark:bg-zinc-900
      opacity-100 dark:opacity-0
    "
  />

  {/* animated dark layer */}
  <div
    className="
      fixed inset-0 -z-10
      transition-opacity duration-900 delay-75 ease-in-out
      bg-zinc-900
      opacity-0 dark:opacity-100
    "
  />

  <Providers>

    <nav className="absolute top-0 left-0 right-0 flex justify-end px-8 py-4">
      <ThemeToggle />
    </nav>

    {children}

  </Providers>

</body>
    </html>
  );
}